# Generated by Django 4.2.14 on 2024-09-18 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('qr_number', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Qr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('times_scanned', models.IntegerField(default=0)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.project')),
            ],
        ),
    ]
